### ISSUE TITLE
Chapter 1 - Stylesheet

### ISSUE THREAD

**Issue by Vorlonos** [PacktPublishing/Django-2-by-Example#26]
Hi,

I might be doing something wrong as I am quite new to programming but shouldn't we change the line:
STATIC_URL = '/static/' to:
STATIC_URL = '/blog/static/' in settings.py as we keep the static directory inside the blog app?
With the first option, editing the stylesheet does not make any changes to the blog, and after changing the line to the '/blog/static/' whenever i change anything in the blog.css file, all the changes are visible on the website.

I would be grateful for an answer.
Thanks

**Comment by rahul7011** [comment]
There is no need to change the  in settings.py as by default STATIC_URL searches for every static directory present in each app,On changing the **STATIC_URL = '/static/' to: STATIC_URL = '/blog/static/'** in settings file django will end up searching for the static files in only blog/static directory and none of the other apps directory and since we are for this particular project is working with only one app therefore changing only STATIC_URL will not cause any change to the project but we should not try this as it's a bad pratice.
