### ISSUE TITLE
Bookrmarklet_launcher.js issue

### ISSUE THREAD

**Issue by GhalyahF** [PacktPublishing/Django-2-by-Example#9]
In dashboard.html, the current way of linking the bookmarklet doesn't work. I am able to drag the button into the bookmarks bar, but the script itself doesn't work. The output to the console shows that for some reason including the script within the href slices the it. The script stops at the first line and appears incomplete. 
The following temporary fix of pasting the script directly + turning it into a button seems to work:

` <p>Drag the following button to your bookmarks toolbar to bookmark images from other websites → <a href="javascript: (function() {
      if (window.myBookmarklet !== undefined) {
        myBookmarklet();
      } else {
        document.body.appendChild(document.createElement('script')).src =
          'https://7605a314.ngrok.io/static/js/bookmarklet.js?r=' +
          Math.floor(Math.random() * 99999999999999999999);
      }
    })();"><button>Bookmark it</button><p> </a>`

**Comment by zenx** [comment]
I had no issues using Safari but behavior might depend on the browser. @GhalyahF your solution writing all JavaScript in one line works well, but I think the `<button>` element is not required. I will update [bookmarklet_launcher.js](https://github.com/PacktPublishing/Django-2-by-Example/blob/master/Chapter05/bookmarks/images/templates/bookmarklet_launcher.js) so that all JavaScript code in a single line.
